---
apiVersion: v1
kind: Template
metadata:
  name: ansible-jupyter-kernel
objects:
- apiVersion: v1
  kind: ConfigMap
  metadata:
    name: ansible-jupyter
  data:
    JUPYTER_TOKEN: "${JUPYTER_TOKEN}"
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    labels:
      app: ansible-jupyter
    name: ansible-jupyter
  spec:
    replicas: 1
    selector:
      app: ansible-jupyter
      deploymentconfig: ansible-jupyter
    strategy:
      activeDeadlineSeconds: 21600
      resources: {}
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        labels:
          app: ansible-jupyter
          deploymentconfig: ansible-jupyter
      spec:
        containers:
        - image: '' 
          imagePullPolicy: Always
          name: ansible-jupyter
          ports:
          - containerPort: 8888
            protocol: TCP
          envFrom:
          - configMapRef:
              name: ansible-jupyter
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - ansible-jupyter
        from:
          kind: ImageStreamTag
          name: ansible-jupyter:latest
      type: ImageChange
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: ansible-jupyter
    name: ansible-jupyter
  spec:
    ports:
    - name: 8888-tcp
      port: 8888
      protocol: TCP
      targetPort: 8888
    selector:
      app: ansible-jupyter
      deploymentconfig: ansible-jupyter
    sessionAffinity: None
    type: ClusterIP
- apiVersion: v1
  kind: Route
  metadata:
    labels:
      app: ansible-jupyter
    name: ansible-jupyter
  spec:
    port:
      targetPort: 8888-tcp
    to:
      kind: Service
      name: ansible-jupyter
      weight: 100
    wildcardPolicy: None
parameters:
- description: The Jupyter token to access the web interface 
  displayName: Jupyter Token 
  name: JUPYTER_TOKEN
  required: true
  generate: expression
  from: "[a-zA-Z0-9]{12}"
